name: Node.js CI Pipeline
# 1. THE TRIGGER: When should this pipeline run?
on:
 push:
   branches: [ "main" ]
# 2. THE RUNNER: GitHub provisions a free, temporary Linux server for us
jobs:
 build-and-test:
   runs-on: ubuntu-latest
   # 3. THE STEPS: The exact terminal commands the server must execute
   steps:
   # Step A: Download our code from the repository onto the temporary server
   - name: Checkout Code
     uses: actions/checkout@v4
   # Step B: Prove the Node.js dependencies can be installed
   - name: Install Dependencies
     run: npm install
   #the new shift left security gate
   - name: Run Unit Tests
     run: npm test
   # Step C: The Ultimate Test - Does our Dockerfile actually compile?
   - name: Test Docker Build
     run: docker build -t test-api-image .
   